/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProgramaNodoPaquete;

/**
 *
 * @author Andres
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        numeroInsertarButton = new javax.swing.JButton();
        numeroInsertarTextField = new javax.swing.JTextField();
        numeroInsertarLabel = new javax.swing.JLabel();
        extraerUltimoButton = new javax.swing.JButton();
        obtenerPrimerButton = new javax.swing.JButton();
        obtenerUltimoButton = new javax.swing.JButton();
        posicionObtenerLabel = new javax.swing.JLabel();
        posicionObtenerTextField = new javax.swing.JTextField();
        posicionObtenerButton = new javax.swing.JButton();
        vacioEstadoButton = new javax.swing.JButton();
        mostrarTamanoButton = new javax.swing.JButton();
        mostrarElementoButton = new javax.swing.JButton();
        vaciarColaButton = new javax.swing.JButton();
        salirButton = new javax.swing.JButton();
        canvas1 = new java.awt.Canvas();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        tituloLabel = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        numeroInsertarButton.setText("Insertar");
        numeroInsertarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroInsertarButtonActionPerformed(evt);
            }
        });

        numeroInsertarTextField.setText("inserte numero");
        numeroInsertarTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroInsertarTextFieldActionPerformed(evt);
            }
        });

        numeroInsertarLabel.setText("Valor a insertar:");

        extraerUltimoButton.setText("Extraer ultimo valor");

        obtenerPrimerButton.setText("Obtener primer valor");
        obtenerPrimerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obtenerPrimerButtonActionPerformed(evt);
            }
        });

        obtenerUltimoButton.setText("Obtener ultimo valor");

        posicionObtenerLabel.setText("Ingrese posicion:");

        posicionObtenerTextField.setText("inserte posicion");

        posicionObtenerButton.setText("Obtener");

        vacioEstadoButton.setText("Estado de la pila");

        mostrarTamanoButton.setText("Tamaño de la pila");

        mostrarElementoButton.setText("Mostrar todos los elementos");
        mostrarElementoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarElementoButtonActionPerformed(evt);
            }
        });

        vaciarColaButton.setText("Vaciar pila");

        salirButton.setText("Salir");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        tituloLabel.setText("Funcionamiento de la pila");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(346, 346, 346))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numeroInsertarLabel)
                            .addComponent(posicionObtenerLabel))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(obtenerPrimerButton)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(posicionObtenerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(posicionObtenerButton))
                            .addComponent(obtenerUltimoButton)
                            .addComponent(salirButton)
                            .addComponent(vaciarColaButton)
                            .addComponent(mostrarElementoButton)
                            .addComponent(mostrarTamanoButton)
                            .addComponent(vacioEstadoButton)
                            .addComponent(extraerUltimoButton)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(numeroInsertarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(numeroInsertarButton)))
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(390, 390, 390)
                        .addComponent(tituloLabel)))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(tituloLabel)
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numeroInsertarButton)
                            .addComponent(numeroInsertarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numeroInsertarLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(extraerUltimoButton)
                        .addGap(13, 13, 13)
                        .addComponent(obtenerPrimerButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(obtenerUltimoButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(posicionObtenerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(posicionObtenerLabel)
                            .addComponent(posicionObtenerButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(vacioEstadoButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mostrarTamanoButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mostrarElementoButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(vaciarColaButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(salirButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numeroInsertarTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroInsertarTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroInsertarTextFieldActionPerformed

    private void obtenerPrimerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obtenerPrimerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_obtenerPrimerButtonActionPerformed

    private void mostrarElementoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarElementoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mostrarElementoButtonActionPerformed

    private void numeroInsertarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroInsertarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroInsertarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Canvas canvas1;
    private javax.swing.JButton extraerUltimoButton;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton mostrarElementoButton;
    private javax.swing.JButton mostrarTamanoButton;
    private javax.swing.JButton numeroInsertarButton;
    private javax.swing.JLabel numeroInsertarLabel;
    private javax.swing.JTextField numeroInsertarTextField;
    private javax.swing.JButton obtenerPrimerButton;
    private javax.swing.JButton obtenerUltimoButton;
    private javax.swing.JButton posicionObtenerButton;
    private javax.swing.JLabel posicionObtenerLabel;
    private javax.swing.JTextField posicionObtenerTextField;
    private javax.swing.JButton salirButton;
    private javax.swing.JLabel tituloLabel;
    private javax.swing.JButton vaciarColaButton;
    private javax.swing.JButton vacioEstadoButton;
    // End of variables declaration//GEN-END:variables
}
